[package]
name = "cattus"
version = "0.1.0"
edition = "2024"


[dependencies]
log = "0.4"
env_logger = "0.11"
itertools = "0.14"
rand = "0.9"
rand_distr = "0.6.0-rc.0"
lazy_static = "1.5.*"
petgraph = "0.8"
clap = { version = "4.5", features = ["derive"] }
ndarray = "0.16"
chess = "3.2.*"
num-traits = "0.2"
metrics = "0.24"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
crossbeam-utils = "0.8.4"


# Optional dependencies for model inference
pyo3 = { version = "0.27", features = ["auto-initialize"], optional = true }
numpy = { version = "0.27", default-features = false, optional = true }
tract-onnx = { version = "0.22", optional = true }
ort = { version = "2.0.0-rc.10", optional = true }
executorch = { version = "0.8", features = [
    "module",
    "tensor-ptr",
], optional = true }
executorch-sys = { version = "0.8", default-features = false, optional = true }
pleco = { version = "0.5.*", optional = true }
# TODO: use tch-rs 0.21.0 when it is released
torch = { package = "tch", git = "https://github.com/LaurentMazare/tch-rs.git", rev = "fde04c49b3e99ce298f401e83aa16705c0ae600d", default-features = false, optional = true }


[features]
default = []
torch-python = ["pyo3", "numpy"]
torch-tch-rs = ["torch"]
onnx-tract = ["tract-onnx"]
onnx-ort = ["ort"]
executorch = ["dep:executorch", "executorch-sys"]
stockfish = ["pleco"]


[[bin]]
name = "cattus"
path = "src/bin/cattus.rs"
required-features = ["stockfish"]

[[example]]
name = "chess_cli_vs_stockfish"
path = "examples/chess_cli_vs_stockfish.rs"
required-features = ["stockfish"]
